### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by Dcell** [karosLi/KKJSBridge#11]
看了源码，楼主挺有心的。
有个小小的建议：
1.抽取核心通信功能
2.添加插件协议，可自定义插件
3.hook的等相关功能，作为无缝插件扩展

**Comment by karosLi** [comment]
1.抽取核心通信功能
这里没有明白你的意思，可否在详细说下
2.添加插件协议，可自定义插件
目前已经有模块协议可以去自定功能了，不知你这里说的插件是指什么呢？
3.hook的等相关功能，作为无缝插件扩展
你说这部分只指，拆成不同的 subspec？
