### ISSUE TITLE
OC端拦截Ajax的网络请求完成后发送回调，但是H5的注入代码"setProperties"却只被调用一次

### ISSUE THREAD

**Issue by cpo007** [karosLi/KKJSBridge#12]
OC这边回调了七个包但是H5断点调试只收到第一个包，请问这是为什么啊？

**Comment by cpo007** [comment]
我发现_XHR的cache并没有真正存入xhr对象，只是保存了id，有可能是这个原因导致无法回调

**Comment by karosLi** [comment]
嗯，你好，你那边是使用最新的 KKJSBridge 吗，你有 demo 吗，我们这边使用都没有问题的哈。最好有 demo 发我就好了，然后指明下是哪个ajax发送失败了。

**Comment by karosLi** [comment]
嗯，你好，你那边是使用最新的 KKJSBridge 吗，你有 demo 吗，我这边使用都没有问题的哈。最好有 demo 发我就好了，然后指明下是哪个ajax发送失败了。

**Comment by karosLi** [comment]
嗯，你好，你那边是使用最新的 KKJSBridge 吗，你有 demo 吗，我这边使用都没有问题的哈。最好有 demo 发我就好了，然后指明下是哪个ajax发送失败了。

**Comment by karosLi** [comment]
嗯，你好，你那边是使用最新的 KKJSBridge 吗，你有 demo 吗，我这边使用都没有问题的哈。最好有 demo 发我就好了，然后指明下是哪个ajax发送失败了。

**Comment by karosLi** [comment]
嗯，你好，你那边是使用最新的 KKJSBridge 吗，你有 demo 吗，我这边使用都没有问题的哈。最好有 demo 发我就好了，然后指明下是哪个ajax发送失败了。

**Comment by cpo007** [comment]
所有的ajax都会被拦截转用AFN发送，然后AFN在调用JS后JS注入代码的断点只能断到一次。
打断点只能看到unfinder报错。
不确定是不是我这边的Web开发人员的问题，只能先关掉了
