### ISSUE TITLE
Remove UIWebView

### ISSUE THREAD

**Issue by ElfSundae** [karosLi/KKJSBridge#13]
苹果审核不允许出现 `UIWebView`，请移除，谢谢。

**Comment by karosLi** [comment]
这里没有用到 UIWebView 的

**Comment by ElfSundae** [comment]
@karosLi 有啊，我们就是上传包被拒了才发现的 https://github.com/karosLi/KKJSBridge/blob/master/KKJSBridge/KKJSBridge/View/Extension/WKWebView+KKWebViewExtension.m#L45-L47

**Comment by karosLi** [comment]
好的，我移除下，多谢提醒。
