### ISSUE TITLE
response 返回html的问题

### ISSUE THREAD

**Issue by dhui68** [karosLi/KKJSBridge#16]
页面请求时如果有跳转地址，没有处理返回是html的情况，导致页面空白

**Comment by karosLi** [comment]
ok，有demo可以调试吗

**Comment by karosLi** [comment]
你好，我补充了下ajax获取html文本的demo，目前是可以获取到的，你使用的是最新的版本吗
![image](https://user-images.githubusercontent.com/6810941/84616426-897fc600-aefe-11ea-985c-bfb1d28a7ce7.png)

**Comment by dhui68** [comment]
> 你好，我补充了下ajax获取html文本的demo，目前是可以获取到的，你使用的是最新的版本吗
> 
> ![image](https://user-images.githubusercontent.com/6810941/84616426-897fc600-aefe-11ea-985c-bfb1d28a7ce7.png)
> 
> 

看见了你的处理方式是通过取到div，然后设置innerText  ，其实我使用hook ajax方式，是为了解决未知页面情况下，进行拦截请求，所以这种情况div是不确定的，有些场景可以使用document.write(xhr.responseText)

**Comment by karosLi** [comment]
那你说的未知页面的场景是什么样的？

**Comment by karosLi** [comment]
可以试下新版本 1.1.2 看看，如果有问题，可以再次打开
