### ISSUE TITLE
大神可以讲一下模块的作用和目的吗

### ISSUE THREAD

**Issue by lichanghong** [karosLi/KKJSBridge#17]
最近在做离线缓存功能，看到您的库之后受益匪浅，但是研究您的代码的时候，发现有个模块的概念。一直没理解加模块是为了什么，以及场景。

假如我要封装一个通用的webview，所有的H5都使用，这时候模块对我来说还是否有意义

**Comment by lichanghong** [comment]
我的微信号：huntaiji  期望您能指导一下，感谢

**Comment by lichanghong** [comment]
callback和event，这俩消息有啥区别

**Comment by karosLi** [comment]
模块主要是用于功能的分类管理，比如你有 界面，导航，业务A，业务B，那这样就可以针对这些功能都封装到自己的模块里去管理，如果没有分模块的话，那相当于所有功能都在一起，代码就会显得很臃肿，也不够清晰。

callback：是JS调用Natvie，希望native能够把处理结果返回到JS侧
event：这个是事件，是Native主动产生一个事件，让JS去监听，比如界面的onResume事件。有点类似JS里的 addEvertLIstener，可以监听浏览器的事件，也可以监听自定义事件。

**Comment by lichanghong** [comment]
感谢大神的热心指导，让我受益匪浅。
关于模块的问题，界面，导航，业务A，业务B是指JS的吗？比如JS的业务A模块，对应iOS的业务A模块，谢谢

**Comment by karosLi** [comment]
> 感谢大神的热心指导，让我受益匪浅。
> 关于模块的问题，界面，导航，业务A，业务B是指JS的吗？比如JS的业务A模块，对应iOS的业务A模块，谢谢

都是natvie里的模块，因为功能都是native提供给js调用

**Comment by lichanghong** [comment]
明白了，感谢大神的不吝赐教 😄
