### ISSUE TITLE
我们项目使用 Fetch api ， 求尽快实现 Fetch hook 功能

### ISSUE THREAD

**Issue by gyf19** [karosLi/KKJSBridge#21]
我们项目使用 Fetch api ， 求尽快实现 Fetch hook 功能。 谢谢

**Comment by dhui68** [comment]
我们项目H5也有fetch，使用NSURLProtocol，WKWebView请求body丢失，哎，天天被领导催，我初步思路是拦截fetch请求，转成ajax，但还是有问题，谁搞定了的，跪求分享下

**Comment by karosLi** [comment]
最近想想看

**Comment by karosLi** [comment]
发布了新的版本，支持fetchhook的beta版本，你们可以试下。
KKJSBridge (1.0.16-fetchhookbeta)

**Comment by gyf19** [comment]
@karosLi  优秀
