### ISSUE TITLE
KKWebView重用导致历史记录异常

### ISSUE THREAD

**Issue by cpo007** [karosLi/KKJSBridge#23]
我描述一下我遇到的问题，我在项目中使用了重用逻辑
`    
self.m_webView = [[KKWebViewPool sharedInstance] dequeueWebViewWithClass:KKWebView.class webViewHolder:self];
`
而在使用重用后初始化进入一个URL地址然后通过内部的链接跳转跳转到下一个地址，接着调用goBack(),此时无异常。
然后在回退到原生页面重新再打开WebView后，此时重用的WebView指针地址是完全一样的，说明是同一个WebView，然后再在index页面进入详情页面的地址时，此时调用goBack无效，查看该页面的backlist，发现它不存在历史的上一个页面。
而这个问题在不使用重用时而是直接new一个新的webview实例对象时不存在。

**Comment by karosLi** [comment]
不能复现你说问题。你们是单页应用，还是多页？
