### ISSUE TITLE
swift崩溃在了设置代理的方法

### ISSUE THREAD

**Issue by herody** [karosLi/KKJSBridge#24]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[KKJSBridgeConfig setAjaxDelegateManager:]: unrecognized selector sent to class 0x1088d56f8'

**Comment by karosLi** [comment]
你那边swift具体是怎么调用的？

**Comment by herody** [comment]
按照demo里写的。用pod一直崩溃，现在我直接把代码拖进去，发现不崩溃了，不知道是什么原因

**Comment by karosLi** [comment]
可以把你demo发我调试下

**Comment by herody** [comment]
试了新版本，没有崩溃了，但是这一块的error不支持传nil，传入可选类型会有点问题

<img width="1107" alt="截屏2020-07-07 上午11 51 14" src="https://user-images.githubusercontent.com/17825454/86705671-b2e8c900-c048-11ea-9abf-dda42dfd5c6e.png">

**Comment by karosLi** [comment]
嗯，这里要改成可选类型

**Comment by karosLi** [comment]
你现在使用的是哪个版本

**Comment by karosLi** [comment]
KKJSBridge 1.1.5 试下这个版本，让error成为了可选类型了

**Comment by herody** [comment]
好的，谢谢啦
