### ISSUE TITLE
支付宝网页支付成功回调页面不会刷新

### ISSUE THREAD

**Issue by Luck-666** [karosLi/KKJSBridge#25]
网页集成了支付宝支付，支付成功后回到APP点击已完成支付页面无响应，麻烦博主看一下哦，谢谢~

**Comment by karosLi** [comment]
1.1.5-beta2

可以试下这个版本看看

**Comment by Luck-666** [comment]
> 1.1.5-beta2
> 
> 可以试下这个版本看看
不行的哦，返回APP直接崩溃了在URLProtocol里面，如下图

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/43161285/86460199-85570380-bd5a-11ea-805e-b6c698a0a805.png">

**Comment by karosLi** [comment]
你那边在这个方法里完整的URL样式发我看下呢

**Comment by karosLi** [comment]
在 1.1.5-beta3 版本里，兼容了下 url 编码的情况，可以试下

**Comment by Luck-666** [comment]
> 你那边在这个方法里完整的URL样式发我看下呢

我是在这个地方写的，你看下哦，但是仅仅是阻止了崩溃，点击已完成付款仍未有效果，代码如图：
<img width="1020" alt="WeChatd38b1e7dbe05b1e42642320433ca5e35" src="https://user-images.githubusercontent.com/43161285/86547328-3338fc80-bf6b-11ea-9a0f-35441f7863be.png">

**Comment by Luck-666** [comment]
> 在 1.1.5-beta3 版本里，兼容了下 url 编码的情况，可以试下

感谢大佬耐心解决问题，测试了1.1.5-beta3 版本，解决了URL编码导致的崩溃问题，但是支付跳转支付宝再返回APP后或者取消支付返回APP，点击已完成付款还是无反应，如图：
<img width="398" alt="image" src="https://user-images.githubusercontent.com/43161285/86547409-80b56980-bf6b-11ea-94ee-9302d97c50d5.png">

**Comment by karosLi** [comment]
把进入这方法时的完整链接发我看下

**Comment by Luck-666** [comment]
好的，一般支付地址有有效期，我邮件私发你一下第三方的地址

**Comment by Luck-666** [comment]
> 把进入这方法时的完整链接发我看下

大佬，邮件已私发链接地址，查收下哦

**Comment by karosLi** [comment]
没有收到链接

**Comment by Luck-666** [comment]
> 没有收到链接

我用Google邮箱又重新发了一次，你确认下有没收到哦，发送的邮箱地址：karosli1314@gmail.com

**Comment by karosLi** [comment]
嗯，收到了

**Comment by karosLi** [comment]
测试链接已经不可用了，无法继续跟，有机会请尝试使用最新版本测试看看，先关掉了。
