### ISSUE TITLE
饿了吗的页面使用ajax后无法正常打开

### ISSUE THREAD

**Issue by ZhangKejun** [karosLi/KKJSBridge#26]
你好：
采用ajax拦截打开 https://entu.ele.me 时候无法正常访问，页面提示错误；
如下图
<img width="1816" alt="image" src="https://user-images.githubusercontent.com/15724876/86459328-32c91780-bd59-11ea-9a85-be492d2294e8.png">
我尝试进行修改：
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/15724876/86459548-86d3fc00-bd59-11ea-9339-0315ac5359aa.png">
访问后，依然报错，如下图：
<img width="1818" alt="image" src="https://user-images.githubusercontent.com/15724876/86459662-b6830400-bd59-11ea-8bae-da7fcf02ccc2.png">

但如果不使用ajax拦截是可以正常出现界面的，如下图：
<img width="328" alt="image" src="https://user-images.githubusercontent.com/15724876/86459881-019d1700-bd5a-11ea-9bd5-a006df957af1.png">

烦请大佬帮忙排查排查，是什么原因导致的呢？

**Comment by dhui68** [comment]
发的啥，看不到图片

**Comment by karosLi** [comment]
应该是不支持 iframe 的原因

1.1.5-beta2 可以试下这个版本看看，这个版本有支持iframe的处理

**Comment by karosLi** [comment]
如果有问题，再开启
