### ISSUE TITLE
清除缓存问题，待验证

### ISSUE THREAD

**Issue by dhui68** [karosLi/KKJSBridge#28]
1.1.5-beta3，KKJSBridgeAjaxURLProtocol.m 117行代码  
- (void)clearRequestBody 方法

请求是异步的，有时候当前请求还没有结束，又有新的请求requestId又重新赋值，所以我觉得clearRequestBody会有问题

**Comment by karosLi** [comment]
新的请求会有新的requestId，不会冲突
