### ISSUE TITLE
可以使用WKURLSchemeHandler替换NSURLProtocol做拦截吗？

### ISSUE THREAD

**Issue by YL-ok** [karosLi/KKJSBridge#34]

**Comment by karosLi** [comment]
目前不会考虑，WKURLSchemeHandler 只支持 iOS 11 以上，目前主流 app 都是 iOS 10 起步的。

如果你不想使用 NSURLProtocol，那可以考虑使用非 NSURLProtocol 方案实现的 ajax hook。

```
pod "KKJSBridge/AjaxHook", "1.1.5-beta10"
```
