### ISSUE TITLE
作者你好，index.ts里面拦截form的submit方法的代码，在KKJSBridge.js里面怎么没有

### ISSUE THREAD

**Issue by MitnickX** [karosLi/KKJSBridge#36]
![image](https://user-images.githubusercontent.com/6338494/90733617-622ee600-e2ff-11ea-9096-9907f4f53b37.png)

图片里面的代码在KKJSBridge.js里面消失了

**Comment by karosLi** [comment]
KKJSBridge.js 是master分支的代码，index.ts 是 newAjax 分支的代码，你是不是看混淆了
