### ISSUE TITLE
开启 AjaxHook 后，H5 没有发起 options 请求

### ISSUE THREAD

**Issue by 372945980** [karosLi/KKJSBridge#41]
AjaxHook 关闭时，打开 H5 页面会请求 options 接口；开启后 Charles 抓包看不到 options 请求了。

**Comment by karosLi** [comment]
有测试链接吗？

**Comment by 372945980** [comment]
https://www.docer.com

**Comment by karosLi** [comment]
这个链接我在浏览器打开也没有OPTIONS请求。

另外我在最新的 1.2.1 版本上测试你这个链接，也没有出现错误。

你那边是使用的最新的版本吗？如果最新的版本也有问题， 可以截图发我看下。

**Comment by gaoruiqing187** [comment]
1.2.1在pod上搜不到。demo里下载的是最新的吗

**Comment by karosLi** [comment]
有的。

![Jietu20201029-120510](https://user-images.githubusercontent.com/6810941/97524223-183d3d00-19df-11eb-96c6-e94bf9cb9185.jpg)
