### ISSUE TITLE
页面加载报错

### ISSUE THREAD

**Issue by wjiuxing** [karosLi/KKJSBridge#45]
用 Demo（AjaxHook），打开上面的地址，页面报错，但是用浏览器打开正常，我试了直接用 WKWebView 写个 demo 也能打开，请帮忙看看呀。

https://www.huawei.com/minisite/mbbf2020/cn/?ic_medium=hwdc&ic_source=corp_event2_mbbf2020

**Comment by karosLi** [comment]
![image](https://user-images.githubusercontent.com/6810941/99020373-6f274280-2599-11eb-9967-fb18d2a891ce.png)
![image](https://user-images.githubusercontent.com/6810941/99020510-be6d7300-2599-11eb-8c14-74d4f37ce7ad.png)
我是了下，可以正常打开，iOS 12.4 和 iOS 14.2 打开都没问题

**Comment by karosLi** [comment]
你不是用的最新的版本吧

**Comment by wjiuxing** [comment]
是最新版，v1.2.3，我直接修改的 KKJSBridgeDemo/KKJSBridgeDemo/ViewController.m 里面的 url。

**Comment by wjiuxing** [comment]
我把 Library/Cookies 删了之后，重新打开 demo，就可以打开这个页面了。

**Comment by karosLi** [comment]
那是登录态的问题？

**Comment by wjiuxing** [comment]
这是一个广告落地页，不需要登录。可能是 cookies 没有设置好吧。我把出错的cookies上传到网盘了。

复制这段内容后打开百度网盘App，操作更方便哦。
链接：https://pan.baidu.com/s/1ZTz4ZKdvh3wZCOJLKar2YA 
提取码：V9sa

**Comment by karosLi** [comment]
你这样传这个cookie，我这看不出来的。我这边还不能复现。你那边有完整的复现步骤吗？

**Comment by wjiuxing** [comment]
我这边模拟器是大概两周前运行过 demo（启动了 server.js），然后我修改了一下 KKJSBridgeDemo/KKJSBridgeDemo/ViewController.m 里面的 url，运行起来就报错了。

如果我把这两个 cookie 文件删了，或者直接 reset 模拟器，再 build，这个页面就能打开了。

**Comment by wjiuxing** [comment]
你替换一下这个 cookie 文件也不能复现吗？

**Comment by karosLi** [comment]
![Uploading image.png…]()
使用你这个cookie替换，返回的是一个403

![Uploading image.png…]()
所以你这个cookie是怎么产生的？

**Comment by karosLi** [comment]
![image](https://user-images.githubusercontent.com/6810941/99245978-7d968800-283f-11eb-8463-dbe72553780d.png)
你给的 cookie 文件，这个 cookie 还没有过期。应该是华为那边自己不认这个 HMF_CI 了。

**Comment by wjiuxing** [comment]
好的，就先这样吧，辛苦了 👍
