### ISSUE TITLE
demo无效果

### ISSUE THREAD

**Issue by ZhangKejun** [karosLi/KKJSBridge#5]
您好，运行demo，发现没有什么效果。也没看到相关日志打印，是需要修改什么地方吗？

**Comment by karosLi** [comment]
嗯，不好意思，我没有说清楚要怎么运行demo。
运行demo步骤：
1、进入 KKJSBridgeDemo/KKJSBridgeDemo/Software/Server 目录
2、基于上面目录打开终端，并运行 node server.js
3、打开 KKJSBridgeDemo/KKJSBridgeDemo.xcworkspace 运行 demo

**Comment by ZhangKejun** [comment]
可以用了，谢谢大兄弟
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Karosli <notifications@github.com&gt;
发送时间: 2019年12月24日 17:38
收件人: karosLi/KKJSBridge <KKJSBridge@noreply.github.com&gt;
抄送: Zhangkejun <604332218@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[karosLi/KKJSBridge] demo无效果 (#5)




嗯，不好意思，我没有说清楚要怎么运行demo。
 运行demo步骤：
 1、进入 KKJSBridgeDemo/KKJSBridgeDemo/Software/Server 目录
 2、基于上面目录打开终端，并运行 node server.js
 3、打开 KKJSBridgeDemo/KKJSBridgeDemo.xcworkspace 运行 demo
