### ISSUE TITLE
百度中搜索天猫后打不开

### ISSUE THREAD

**Issue by boost-some-one** [karosLi/KKJSBridge#51]
首先感谢作者做出了这么有用的demo，对我启发很大。
但在初步测试使用过程中，发现一个小BUG：
使用本demo，在百度中搜索"天猫“，显示结果后，结果中的天猫链接打不开（打开后白屏）
请问这个是什么原理？有没有相应的解决办法？

**Comment by karosLi** [comment]
嗯，确实打不开，有空再看下了

**Comment by karosLi** [comment]
![image](https://user-images.githubusercontent.com/6810941/104338748-c9a93480-5531-11eb-9ae5-c8658f05b7bb.png)
淘宝的重定向请求，不要拦截，就不会白屏了
