### ISSUE TITLE
iOS 13发起GET请求时不能携带body导致请求失败

### ISSUE THREAD

**Issue by SQsteven** [karosLi/KKJSBridge#52]
我的解决方案是在KKJSBridgeAjaxURLProtocol中，判断是否是GET请求，是的话不加Body。请问有没有更好的解决方案？
(bodyReqeust && ![self.requestHTTPMethod isEqualToString:@"GET"])

**Comment by karosLi** [comment]
你的问题是 GET 请求携带了 Body，导致请求失败吗？

**Comment by SQsteven** [comment]
对，进入页面后，web端又发起了一次get请求，请求直接被返回错误了。
现在又有新的问题，进入web页，web端又发起了一个get请求，请求没有发出去

**Comment by SQsteven** [comment]
跟web端沟通了一下，用的是axios请求的

**Comment by karosLi** [comment]
get 请求是怎么产生的 body ？

**Comment by SQsteven** [comment]
这个不太清楚。问web端那边也没说清楚

**Comment by karosLi** [comment]
可以在 safari 里，debug send 方法，看看 send 的时候，是不是 get 请求额外添加了 body

**Comment by Huiz110** [comment]
这个问题我们也碰到过，H5 那边发起 GET 请求带 body 是不会报错的，我们这边现在是在hook 后原生发起请求时，判断是 GET 则清空 body

**Comment by karosLi** [comment]
1.3.9 版本已经修复了
