### ISSUE TITLE
模拟器iphone8 iOS13白屏

### ISSUE THREAD

**Issue by FoneG** [karosLi/KKJSBridge#57]
测试链接：http://www.baidu.com
频率：必现
使用上面的模拟器设备加载测试链接，会不停调用webView:decidePolicyForNavigationAction:decisionHandler: 来重定向，导致白屏

**Comment by karosLi** [comment]
真机上是好的吗？

**Comment by FoneG** [comment]
试了下手上的2个设备，iphone6  12.4.3  白屏，iPhone XS 14.01正常

PS：能否加一下WX，发送到你邮箱了

**Comment by karosLi** [comment]
我在demo里加载 http://www.baidu.com，模拟器（iOS14.2）和真机（iPhone 11 iOS14.2 和 iPhone 6P iOS12.4）都不会白屏
