### ISSUE TITLE
补充一个兼容代码，看是否有帮助。

### ISSUE THREAD

**Issue by ZhangKejun** [karosLi/KKJSBridge#7]
解决本地资源的ajax请求漏洞：
修改原因：
如果通过ajax请求发起本地资源的获取，比如url="abc.html"; href="file://test/index.html"
按照原来的代码，最终获取的地址为url="file://abc.html";
但实际应用获取到的url="file://test/abc.html"才对；

修改文件为：KKJSBridgeModuleXMLHttpRequestDispatcher.m
修改如下：
- (void)open:(KKJSBridgeEngine *)engine params:(NSDictionary *)params responseCallback:(void (^)(NSDictionary *responseData))responseCallback {
    NSNumber *objectId = params[@"id"];
    KKJSBridgeXMLHttpRequest *xhr = [self getXHR:engine.webView objectId:objectId];
    if (!xhr) {
        xhr = [self generateXHR:engine objectId:objectId responseCallback:responseCallback];
    }
    NSString *method = params[@"method"];
    NSString *url = params[@"url"];
    NSString *userAgent = params[@"useragent"] ? params[@"useragent"] : @"iOS";
    NSString *referer = params[@"referer"];
    NSString *scheme = params[@"scheme"];
    NSString *host = params[@"host"];
    NSString *port = params[@"port"] ? params[@"port"] : @"";
    NSString *href = params[@"href"];
  
    NSURL *nativeURL = [NSURL URLWithString:url];
    if (!nativeURL.scheme) {
        
        /*------------兼容的代码 start------------*/
         // 说明是相对路径，一般是资源文件
         NSString* path = [href componentsSeparatedByString:@"."][0]; // 按“.”进行分割，获取第一个字符串 需要考虑类似地址：file://xxx/index.html#/testkey?abc=xxx
         path = [path stringByDeletingLastPathComponent]; // 删除最后一个“/”之后的内容
        
         if (![url hasPrefix:@"/"]){
             path = [NSString stringWithFormat:@"%@/",path];
         }
         // 获取当前目录，然后拼接
         url = [NSString stringWithFormat:@"%@%@",path,url];
         
         /*-----------兼容的代码 end-------------*/
        
//        if (nativeURL.pathComponents > 0) {
//            if (nativeURL.host) {
//                url = [NSString stringWithFormat:@"%@%@",scheme, url];
//            } else {
//                if ([url hasPrefix:@"/"]) {// 处理 【/】情况
//                    NSString *tmpPath = url;
//                    NSString *tmpPort = port.length > 0 ? [NSString stringWithFormat:@":%@", port] : @"";
//                    url = [NSString stringWithFormat:@"%@//%@%@%@",scheme, host, tmpPort, tmpPath];
//                } else { // 处理 【./】 【../】 【../../】和前面没有前缀的情况
//                    url = [[href stringByAppendingPathComponent:url] stringByStandardizingPath];
//                }
//            }
//        } else {
//            url = href;
//        }
    }
    
    [xhr open:method url:url userAgent:userAgent referer:referer];
}

**Comment by karosLi** [comment]
嗯，你这个我要先测试下

**Comment by karosLi** [comment]
你好，我不太清楚，你是需要ajax请求一个本地资源吗，这是什么样的场景？

**Comment by ZhangKejun** [comment]
> 你好，我不太清楚，你是需要ajax请求一个本地资源吗，这是什么样的场景？

我这边的场景是浏览器加载网页，网页可能是本地地址，也可能是网络地址；然后就遇到下面这两种情况，目前你的代码满足不了，所以我做了调整。上次的代码有缺陷，这次又做了一些调整；

    NSURL *nativeURL = [NSURL URLWithString:url];
    if (!nativeURL.scheme) {
        /*------------兼容的代码 start------------*/
        // 说明是相对路径，一般是资源文件
//        示例1
//        {
//            async = 1;
//            host = "m.feng1.com";
//            href = "https://m.feng1.com/mall/app/index.html?channel=xxx&ddsds=ewew2222";
//            id = 632;
//            method = GET;
//            port = "";
//            referer = "<null>";
//            scheme = "https:";
//            url = "/api/mall/channelConfig/getChannelThemeConfig?channel=SFIM&_=1578133077103";
//            useragent = "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A366";
//        }
//
//        示例2
//        {
//            async = 1;
//            host = "";
//            href = "file:///Users/xxxx/Library/Developer/CoreSimulator/Devices/B9133CAF-51E9-456E-92F6-FAC6EFC676AB/data/Containers/Data/Application/5BCBB3E7-A35F-4BCD-89B7-A79474C0E2C8/Documents/c6a5a31f3f1d9e446353e0425ab55c3e/2e6cda38b47d8c6ec672a1ed4f66cfe8/b8c37e33defde51cf91e1e03e51657da/UnityFile/Cache/serviceApp/packages/salary/f99bb68cfd2680c098a287fca1182030/www/index.html#/dsdsds/ddd?key=xxx&eewwe";
//            id = 496;
//            method = GET;
//            port = "";
//            referer = "<null>";
//            scheme = "file:";
//            url = "views/salaryInquiry/ssf-account-edit.html";
//            useragent = "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16A366";
//        }
        
        // 先按照?截取，然后按照#截取
        NSString* path = [href componentsSeparatedByString:@"?"][0]; // 按“?”进行分割，获取第一个字符串
        path = [path componentsSeparatedByString:@"#"][0]; // 按“#”进行分割，获取第一个字符串
        path = [path stringByDeletingLastPathComponent]; // 删除最后一个“/”之后的内容，获取到当前文件的相对路径

        if ([scheme hasPrefix:@"file:"]) {
            // 本地相对路径
            if (![url hasPrefix:@"/"]){
                path = [NSString stringWithFormat:@"%@/",path];
            }
            // 完整路径
            url = [NSString stringWithFormat:@"%@%@",path,url];
        }else{
            // 网络相对路径
            if (![url hasPrefix:@"/"]){
               url = [NSString stringWithFormat:@"%@%@",path,url];
            }else {
               // 网络路径，拼接host
               NSString *tmpPort = port.length > 0 ? [NSString stringWithFormat:@":%@", port] : @"";
               url = [NSString stringWithFormat:@"%@//%@%@%@",scheme, host, tmpPort, url];
            }
        }
        /*-----------兼容的代码 end-------------*/
        /*-----------下面是你原来的代码--------*/
//        NSFileManager* fm = [NSFileManager defaultManager];
//
//        if (nativeURL.pathComponents > 0) {
//            if (nativeURL.host) {
//                url = [NSString stringWithFormat:@"%@%@",scheme, url];
//            } else {
//                NSString *tmpPath = [url hasPrefix:@"/"] ? url : [NSString stringWithFormat:@"/%@", url];
//                NSString *tmpPort = port.length > 0 ? [NSString stringWithFormat:@":%@", port] : @"";
//                url = [NSString stringWithFormat:@"%@//%@%@%@",scheme, host, tmpPort, tmpPath];
//            }
//        } else {
//            url = href;
//        }
        
    }

**Comment by karosLi** [comment]
嗯，你提一个PR吧

**Comment by ZhangKejun** [comment]
> 嗯，你提一个PR吧

我好像提交不了，我这边改动的代码是融合在我们自己工程的。公司网络不让提交内容到github，抱歉

**Comment by ZhangKejun** [comment]
场景一：
当网页中出现<iframe>标签时，对于iframe中代码发出的请求现在的代码无法正确获取请求实例，导致无法正常返回结果，界面卡死；修改文件为：KKJSBridge.js
/**
         * 用于处理来自 native 的异步回调
         */
        _XHR.setProperties = function (jsonString) {
            var jsonObj = JSON.parse(jsonString);
            var id = jsonObj.id;
            var xhr = _XHR.cache[id];
           // -------------- 开始修改的地方-------------
            console.log("id---%o",id);
            console.log("xhr---%o",xhr);
            if (xhr == undefined) {
                // 尝试从iframe中获取
                var tmpIframes = document.getElementsByTagName("iframe");
                if (tmpIframes && tmpIframes.length > 0){
                    var tmpIframe,tmpXhr;
                    for (var i in tmpIframes){
                        tmpIframe = tmpIframes[i];
                        if (tmpIframe && typeof(tmpIframe) === 'object' ){
                            tmpXhr = tmpIframe.contentWindow._XHR.cache[id];
                            if (tmpXhr && tmpXhr != undefined){
                                xhr = tmpXhr;
                                console.log("xhr--ifame---%o",xhr);
                                break;
                            }
                        }
                    }
                }
            }
            
            if (xhr && typeof(xhr) === 'object') {
                if (jsonObj.readyState === xhr.DONE) {
                    // 防止重复利用 xhr 对象发送请求而导致 id 不变的问题
                    xhr.isCached = false;
                }
// -----------修改结束---------------
                // 保存回调对象，对象子属性的处理放在了 hook 里。因为 xhr 代理对象的可读属性（readyState,status,statusText,responseText）都是从实际 xhr 拷贝过来的，相应的我们也是不能直接对这些可读属性赋值的
                xhr.callbackProperties = jsonObj;
                if (xhr.onreadystatechange) {
                    xhr.onreadystatechange();
                }
                // 因为不能直接赋值给 xhr 的可读属性，所以这里是使用回调对象的属性来判断
                if (xhr.callbackProperties.readyState === xhr.LOADING && xhr.onprogress) {
                    xhr.onprogress();
                }
                if (xhr.callbackProperties.readyState === xhr.DONE) {
                    if (xhr.onload) {
                        xhr.onload();
                    }
                
                    var load = document.createEvent("Events");
                    load.initEvent("load");
                    xhr.dispatchEvent(load);
                }
            }
        };
...... 后面省略

**Comment by ZhangKejun** [comment]
场景二：
当访问的接口或者页面是https请求时，后台采用的是自定义证书时。目前的代码会爆出错误，导致界面无法正常显示；修改文件：KKJSBridgeXMLHttpRequest.m
在sessionDataDelgate中增加如下代码：
// ----------增加的代码----------
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler {
    // 解决自建证书无法访问的问题
    if (![challenge.protectionSpace.authenticationMethod isEqualToString:@"NSURLAuthenticationMethodServerTrust"]) {
        return;
    }
    NSURLCredential *credential = [[NSURLCredential alloc] initWithTrust:challenge.protectionSpace.serverTrust];
    completionHandler(NSURLSessionAuthChallengeUseCredential,credential);
}
// ----------增加的代码----------

**Comment by ZhangKejun** [comment]
> 嗯，你提一个PR吧

已经提交，请查收。顺带提交了一些其他的内容

**Comment by karosLi** [comment]
嗯，好的，不好意思，这么久才回复。我review了下，你的提交，也给了下建议，你看看呢。

**Comment by karosLi** [comment]
现在没有路径问题了
